baseURL = 'https://quotesystemx.space/'
languageCode = 'en'
title = 'QuoteSystemX Documentation'

[module]
  [[module.imports]]
    path = 'github.com/google/docsy'

[params]
  description = "Centralized documentation for QuoteSystemX company"

[ui]
  [ui.feedback]
    enable = false
  [ui.versions_menu]
    enable = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

